theme: jekyll-theme-cayman

# Setup

title:        The Signature Method in Machine Learning

tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Andrey Kormilitzin
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate
  
# Google services
google_analytics: UA-80718101-1

#Others
markdown: kramdown
