theme: jekyll-theme-cayman

# Setup
---
title:        The Signature Method 
subtitle:             in Machine Learning
---
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Andrey Kormilitzin
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
